#!/usr/bin/env python3
"""The Pet's parts for the website: src/apps/pet/parts.h (and the layer names and default look in pet_logic.h)
-> site/pet-parts.js, so the Tools page draws exactly what the device draws. Run after changing the parts:

  python3 tools/pet/export.py          writes site/pet-parts.js
  python3 tools/pet/export.py --check  fails if site/pet-parts.js is out of date
"""
import json, os, re, sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
parts_h = open(os.path.join(root, "src/apps/pet/parts.h")).read()
logic_h = open(os.path.join(root, "src/apps/pet/pet_logic.h")).read()
out_path = os.path.join(root, "site/pet-parts.js")


def parts(block):
    """[{name, rows}] from the C initialiser of one array or single part."""
    found = []
    for name, body in re.findall(r'\{\s*"([^"]+)",\s*\{(.*?)\}\s*\}', block, re.S):
        rows = re.findall(r'"([#o.]{32})"', body)
        assert len(rows) == 32, f"{name}: {len(rows)} rows"
        found.append({"name": name, "rows": rows})
    return found


def array(name):
    m = re.search(rf"static const PetPart {name}\[\] = \{{(.*?)\n\}};", parts_h, re.S)
    assert m, name
    return parts(m.group(1))


layer_names = re.findall(r'"([A-Za-z]+)"', re.search(r"LAYER_NAMES\[LAYERS\] = \{(.*?)\};", logic_h).group(1))
default = [int(x) for x in re.search(r"DEFAULT_LOOK = \{\{([\d,\s]+)\}\}", logic_h).group(1).split(",")]
happy = int(re.search(r"HAPPY_EYES = (\d+)", logic_h).group(1))
closed = parts(re.search(r"EYES_CLOSED = (\{.*?\}\});", parts_h, re.S).group(1))[0]
layers = [{"name": n, "parts": array(a)} for n, a in zip(layer_names, ["BODIES", "EYES", "MOUTHS", "HATS", "EXTRAS"])]

js = ("// Generated by tools/pet/export.py from src/apps/pet/parts.h and pet_logic.h: don't edit, run the script.\n"
      "// Each part is 32 rows of 32 characters: '#' ink, 'o' paper (covers what is under it), '.' see-through.\n"
      f"export const LAYERS = {json.dumps(layers, separators=(',', ':'))};\n"
      f"export const EYES_CLOSED = {json.dumps(closed, separators=(',', ':'))};\n"
      f"export const DEFAULT_LOOK = {json.dumps(default)};\n"
      f"export const HAPPY_EYES = {happy};\n")
if "--check" in sys.argv:
    current = open(out_path).read() if os.path.exists(out_path) else ""
    if current != js:
        sys.exit("site/pet-parts.js is out of date: run python3 tools/pet/export.py")
    print("site/pet-parts.js is up to date")
else:
    open(out_path, "w").write(js)
    print(f"wrote site/pet-parts.js: {', '.join(f'{l['name']} {len(l['parts'])}' for l in layers)}")
