#!/usr/bin/env python3
"""TTF -> Adafruit GFX font header (printable ASCII), like Adafruit's fontconvert, using Pillow.

  python3 tools/gfxfont.py FreeSans.ttf 7 FreeSans7pt7b > src/core/FreeSans7pt7b.h

Sizes are points at 141 dpi, as in fontconvert, so 9 here matches Adafruit's FreeSans9pt7b.
"""
import sys

from PIL import Image, ImageDraw, ImageFont

ttf, pt, name = sys.argv[1], float(sys.argv[2]), sys.argv[3]
font = ImageFont.truetype(ttf, round(pt * 141 / 72))
first, last = 0x20, 0x7E

bitmap, glyphs = [], []
for code in range(first, last + 1):
    ch = chr(code)
    left, top, right, bottom = font.getbbox(ch, anchor="ls")
    w, h = max(0, right - left), max(0, bottom - top)
    bits = []
    if w and h:
        im = Image.new("1", (w, h), 0)
        d = ImageDraw.Draw(im)
        d.fontmode = "1"  # no anti-aliasing: one bit per pixel, like fontconvert's mono render
        d.text((-left, -top), ch, font=font, fill=1, anchor="ls")
        box = im.getbbox()  # trim blank edges, as fontconvert's tight bitmaps
        if box:
            im = im.crop(box)
            left, top = left + box[0], top + box[1]
            w, h = im.size
            bits = [im.getpixel((x, y)) for y in range(h) for x in range(w)]
        else:
            w = h = 0
    offset = len(bitmap)
    for i in range(0, len(bits), 8):
        byte = 0
        for j, b in enumerate(bits[i:i + 8]):
            byte |= (1 if b else 0) << (7 - j)
        bitmap.append(byte)
    # fontconvert's yOffset is 1 - bitmap_top, one row lower than the outline: match it so sizes mix evenly
    glyphs.append((offset, w, h, round(font.getlength(ch)), left, top + 1, ch))

line_height = font.font.height  # the face's line spacing, as fontconvert's size->metrics.height
print(f"// {name}: generated by tools/gfxfont.py from GNU FreeFont {ttf.split('/')[-1]} (GPL-3.0-or-later with font exception)")
print("#pragma once\n#include <Adafruit_GFX.h>\n")
print(f"const uint8_t {name}Bitmaps[] PROGMEM = {{")
for i in range(0, len(bitmap), 16):
    print("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
print("};\n")
print(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
for off, w, h, adv, xo, yo, ch in glyphs:
    comment = ch if ch not in "\\" else "backslash"
    print(f"  {{{off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d}}},  // 0x{ord(ch):02X} '{comment}'")
print("};\n")
print(f"const GFXfont {name} PROGMEM = {{(uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs, 0x{first:02X}, 0x{last:02X}, {line_height}}};")
